name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout do código com suporte a submódulos
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Instalação de dependências e execução dos testes
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: true           # Instalar dependências automaticamente
          runTests: true          # Executar os testes automaticamente
